"""baseline users schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-11 07:58:23.348373

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sg_event_id', sa.String(length=64), nullable=False),
    sa.Column('sg_message_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('sg_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_sg_event_id'), ['sg_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_event_sg_message_id'), ['sg_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_sg_timestamp'), ['sg_timestamp'], unique=False)

    op.create_table('email_suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_suppression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_suppression_email'), ['email'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=40), nullable=True),
    sa.Column('api_tier', sa.String(length=32), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_codes_json', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('last_location_lat', sa.Float(), nullable=True),
    sa.Column('last_location_lng', sa.Float(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_totp_code', sa.String(length=10), nullable=True),
    sa.Column('last_totp_code_at', sa.DateTime(), nullable=True),
    sa.Column('email_alerts_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_api_key_hash'), ['api_key_hash'], unique=True)

    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=True),
    sa.Column('key_prefix', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_user_id'), ['user_id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_user_id'), ['user_id'], unique=False)

    op.create_table('submit_location_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lat_bucket', sa.Float(), nullable=False),
    sa.Column('lng_bucket', sa.Float(), nullable=False),
    sa.Column('in_pl', sa.Boolean(), nullable=False),
    sa.Column('browser_class', sa.String(length=32), nullable=True),
    sa.Column('api_tier', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submit_location_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submit_location_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submit_location_event_session_hash'), ['session_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_submit_location_event_user_id'), ['user_id'], unique=False)

    op.create_table('user_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('alerting_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_coverage_state', sa.Text(), nullable=True),
    sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_location_user_id'), ['user_id'], unique=False)

    op.create_table('user_station_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_location_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('centre_lat', sa.Float(), nullable=False),
    sa.Column('centre_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('stations_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_location_id'], ['user_location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_station_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_station_snapshot_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_station_snapshot_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_station_snapshot_user_location_id'), ['user_location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_station_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_station_snapshot_user_location_id'))
        batch_op.drop_index(batch_op.f('ix_user_station_snapshot_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_station_snapshot_taken_at'))

    op.drop_table('user_station_snapshot')
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_location_user_id'))

    op.drop_table('user_location')
    with op.batch_alter_table('submit_location_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submit_location_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_submit_location_event_session_hash'))
        batch_op.drop_index(batch_op.f('ix_submit_location_event_created_at'))

    op.drop_table('submit_location_event')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))

    op.drop_table('audit_event')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_key_key'))

    op.drop_table('api_key')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_key_hash'))
        batch_op.drop_index(batch_op.f('ix_user_api_key'))

    op.drop_table('user')
    with op.batch_alter_table('email_suppression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_suppression_email'))

    op.drop_table('email_suppression')
    with op.batch_alter_table('email_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_event_sg_timestamp'))
        batch_op.drop_index(batch_op.f('ix_email_event_sg_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_event_sg_event_id'))
        batch_op.drop_index(batch_op.f('ix_email_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_email_event_email'))
        batch_op.drop_index(batch_op.f('ix_email_event_created_at'))

    op.drop_table('email_event')
    # ### end Alembic commands ###
